### ISSUE TITLE
A fork is more advanced than this repository

### ISSUE THREAD

**Issue by sticky-note** [deathowl/certbot-vault-plugin#4]
Hi @deathowl,
The way `hvac` is used in this repository is outdated
Here is a fork that seems to be more actual and works for us with certbot `1.12` and vault `1.6.0`
-> https://github.com/vitalvas/certbot-vault-plugin

Unfortunately, this fork was recently archived and we want to update our certbot to last version and it seems that we have to update plugin boilerplate code of this fork that recently changed with last versions of certbot.

How can we proceed to have an up-to-date flavour of this repo `certbot-vault-plugin` ?

Solution that should match is:
1) [ ] Tag a version of actual code
2) [ ] Merge modifications of `vitalvas/certbot-vault-plugin`
3) [ ] Tag a new version
4) [x] Make modification of plugin boilerplate code to permit to run this plugin with recent versions of `hvac`
5) [ ] Tag `1.0.0` ?

I can personnaly contribute to step 4 but you @deathowl is owner of this repo and have to decide what to do outside this step and balance pertinence of other steps
Look forwarding to reading you very soon.
Sam

**Comment by sticky-note** [comment]
Hi @deathowl, done task 4 on `vitlvas` fork -> https://github.com/vitalvas/certbot-vault-plugin/pull/1

**Comment by deathowl** [comment]
I'll merge `vitalvas/certbot-vault-plugin` into mine and then merge your PR too later this weekend

**Comment by deathowl** [comment]
Done
