### ISSUE TITLE
Release on Pypi

### ISSUE THREAD

**Issue by sticky-note** [deathowl/certbot-vault-plugin#5]
Hi @deathowl, is it possible to do a release on PyPI in order to reflect new changes of @vitalvas and me with an official `pip` installation.
https://pypi.org/project/certbot-vault
Thanks

**Comment by deathowl** [comment]
yes! will do in a second!

**Comment by deathowl** [comment]
https://pypi.org/project/certbot-vault/#history done

**Comment by sticky-note** [comment]
@deathowl Wonderful, Thanks
